[workspace]
members = ["orderbook"]

resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.200", features = ["derive"] }
thiserror = "1.0.31"

[workspace.package]
version = "0.1.0"
edition = "2021"
